# Generated by Django 5.0.1 on 2024-02-23 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('City', '0002_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='City.city', verbose_name='Şəhər'),
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='City.city', verbose_name='Şəhər / Rayon')),
            ],
            options={
                'verbose_name_plural': 'Kəndlər',
            },
        ),
    ]
