# Generated by Django 5.0.1 on 2024-02-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ad')),
                ('surname', models.CharField(max_length=50, verbose_name='Soyad')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Mesaj')),
                ('show', models.BooleanField(default=False, verbose_name='Saytda görülsün')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Rəylər',
            },
        ),
    ]
