# Generated by Django 5.0.1 on 2024-02-07 22:03

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Şəkil')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('description', tinymce.models.HTMLField(verbose_name='Məzmun')),
                ('is_active', models.BooleanField(default=False, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Müəllif')),
            ],
            options={
                'verbose_name_plural': 'Xəbərlər',
            },
        ),
    ]
