# Generated by Django 5.0.1 on 2024-02-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_newsmodel_tags'),
        ('NewsTag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='NewsTag.newstagmodel', verbose_name='Teqlər'),
        ),
    ]
