# Generated by Django 5.0.1 on 2024-02-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_alter_newsmodel_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='news-covers/', verbose_name='Şəkil'),
        ),
    ]
