# Generated by Django 5.0.1 on 2024-02-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_alter_newsmodel_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SLUQ'),
        ),
    ]
