# Generated by Django 5.0.1 on 2024-01-30 15:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='announcement/', verbose_name='Əsas şəkil')),
                ('title', models.CharField(max_length=225, verbose_name='Başlıq')),
                ('currency', models.CharField(choices=[('DOLLAR', 'DOLLAR'), ('MANAT', 'MANAT')], default='MANAT', max_length=10, verbose_name='Valyuta')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='Qiymət')),
                ('description', models.TextField(verbose_name='Açıqlama')),
                ('room_count', models.SmallIntegerField(verbose_name='Otaq sayı')),
                ('area', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Elan sahibi')),
            ],
            options={
                'verbose_name_plural': 'Elanlar',
            },
        ),
    ]
