# Generated by Django 5.0.1 on 2024-02-22 20:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of', models.BooleanField(default=False, verbose_name='Elan növu')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='AnnouncementMainPics/', verbose_name='Əsas şəkil')),
                ('title', models.CharField(max_length=225, verbose_name='Başlıq')),
                ('currency', models.CharField(choices=[('DOLLAR', 'DOLLAR'), ('MANAT', 'MANAT')], default='MANAT', max_length=10, verbose_name='Valyuta')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='Qiymət')),
                ('the_initial_payment', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='İlkin ödəniş')),
                ('description', models.TextField(verbose_name='Açıqlama')),
                ('room_count', models.SmallIntegerField(verbose_name='Otaq sayı')),
                ('area', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='Sahə')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ünvan')),
                ('slug', models.CharField(blank=True, max_length=255, null=True, verbose_name='SLUG')),
                ('has_internet', models.BooleanField(default=False, verbose_name='İnternet qoşulub')),
                ('has_gas', models.BooleanField(default=False, verbose_name='Qaz çəkilib')),
                ('has_electricity', models.BooleanField(default=False, verbose_name='Elektriklı təchiz olunub')),
                ('has_water', models.BooleanField(default=False, verbose_name='Su çəkilib')),
                ('has_water_tank', models.BooleanField(default=False, verbose_name='Əlavə su çəni var')),
                ('has_combi', models.BooleanField(default=False, verbose_name='Kombi var')),
                ('renovated', models.BooleanField(default=False, verbose_name='Təmirlidir')),
                ('furnished', models.BooleanField(default=False, verbose_name='Əşyalıdır')),
                ('is_active', models.BooleanField(default=False, verbose_name='Elan aktivdir')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Elanlar',
            },
        ),
        migrations.CreateModel(
            name='AnnouncementPics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='AnnouncementPics/', verbose_name='Şəkil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Elan şəkilləri',
            },
        ),
    ]
