# Generated by Django 5.0.1 on 2024-01-31 21:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementmodel',
            name='area',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='Sahə'),
        ),
    ]
