# Generated by Django 5.0.1 on 2024-02-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Announcement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementmodel',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SLUG'),
        ),
    ]
