# Generated by Django 5.0.1 on 2024-02-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Announcement', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcementmodel',
            name='location',
        ),
        migrations.AddField(
            model_name='announcementmodel',
            name='has_elevator',
            field=models.BooleanField(default=False, verbose_name='Lift var'),
        ),
    ]
