# Generated by Django 5.0.1 on 2024-02-24 03:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Announcement', '0003_remove_announcementmodel_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementmodel',
            name='apartment',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mənzil nömrəsi'),
        ),
        migrations.AddField(
            model_name='announcementmodel',
            name='floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mərtəbə'),
        ),
        migrations.AddField(
            model_name='announcementmodel',
            name='floor_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mərtəbə sayı'),
        ),
        migrations.AlterField(
            model_name='announcementmodel',
            name='the_initial_payment',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='İlkin ödəniş'),
        ),
    ]
