# Generated by Django 5.0.1 on 2024-02-07 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='show',
        ),
    ]
