# Generated by Django 5.0.1 on 2024-01-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0002_alter_about_facebook_alter_about_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Haqqımızda səhifəsi üçün şəkil'),
        ),
    ]
