# Generated by Django 5.0.1 on 2024-01-29 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_agent',
        ),
    ]
