# Generated by Django 5.0.1 on 2024-01-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_alter_customuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='facebook',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='instagram',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='İnstagram'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pinterest',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Pinterest'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tiktok',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='TikTok'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='twitter',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vimeo',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Vimeo'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='youtube',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='YouTube'),
        ),
    ]
