# Generated by Django 5.0.1 on 2024-01-31 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_customuser_facebook_customuser_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Yaşadığı ünvan'),
        ),
    ]
